syntax = "proto3";

package ra2yrproto.commands;

import "ra2yrproto/ra2yr.proto";

message UnitOrder {
  repeated uint32 object_addresses = 1;
  ra2yrproto.ra2yr.UnitAction action = 2;
  uint32 target_object = 3;
  ra2yrproto.ra2yr.Coordinates coordinates = 4;
  uint32 expected_native_id = 5;
  uint32 expected_house = 6;
  uint32 basis_frame = 7;
  uint32 expected_target_native_id = 8;
  uint32 expected_target_house = 9;
  ra2yrproto.ra2yr.AbstractType expected_target_type = 10;
}

message ProduceOrder {
  ra2yrproto.ra2yr.ObjectTypeClass object_type = 1;
  ra2yrproto.ra2yr.ProduceAction action = 2;
}

message PlaceBuilding {
  ra2yrproto.ra2yr.Object building = 1;
  ra2yrproto.ra2yr.Coordinates coordinates = 2;
}
